name: first
on: [push]
jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: echo "Job 1 - Step One"
      - name: Step Two
        run: echo "Job 1 - Step Two"
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
      - name: Step One
        run: echo "Job 2 - Step One"
      - name: Step Two
        run: echo "Job 2 - Step Two"